# Generated by Django 4.0.3 on 2022-05-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
